name: Prueba de Workflow Manual

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Un paso de prueba
        run: echo "Este es un workflow de prueba con un nombre nuevo."
